# Generated by Django 3.2.9 on 2021-12-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='nama',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
